<?php

namespace Jasoft\Viringo\CoreBundle\Repository;

/**
 * SystemConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemConfigRepository extends EntityRepository
{
    /**
     * Cuenta todos los duplicados de la entidad
     * @param \Jasoft\Viringo\CoreBundle\Entity\SystemConfig $entity
     * @param boolean $exclude Indica si la entidad actual se debe excluir de la búsqueda
     *                          (falso por defecto, lo cual significa que se usaría en una inserción)
     * @return integer
     */
    public function findDuplicates($entity, $exclude=false) {
        $qb=$this->createQueryBuilder('s');
        $qb->where('s.name = :name')
             ->setParameters(array('name'=>$entity->getName()))
             ->setMaxResults(1);
        if ($exclude) {
            $qb->andWhere('s.id != :id')
                ->setParameter('id', $entity->getId());
        }
        $duplicateEntity=$qb->getQuery()->execute();
        if(sizeof($duplicateEntity)>0)return $duplicateEntity[0];
        else return null;
    }
}
