<?php

namespace Jasoft\Viringo\CoreBundle\Repository;

/**
 * SystemLocalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemLocalUserRepository extends \Jasoft\Viringo\CoreBundle\Repository\EntityRepository
{
    
    public function getSystemLocalUserByName($userName) {
        $qb=$this->createQueryBuilder('e');
        $expr=$qb->expr();
        $qb
            ->join('e.systemUser', 'su')
            ->where($expr->eq('su.username', $expr->literal($userName)))
        ;
        return $qb->getQuery()->getSingleResult();
    }
}
