<?php

namespace Jasoft\Viringo\CoreBundle\Repository;

/**
 * SystemLocalUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemLocalUserRepository extends \Jasoft\Viringo\CoreBundle\Repository\EntityRepository
{
}
