<?php

namespace Jasoft\Viringo\CoreBundle\Repository;


/**
 * SystemEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemEntityRepository extends \Jasoft\Viringo\CoreBundle\Repository\EntityRepository
{
    
}
